version: '3.8'

services:
  nextjs-app-1:
    build: .
    ports:
      - "3001:3000"
    env_file:
      - .env

  nextjs-app-2:
    build: .
    ports:
      - "3002:3000"
    env_file:
      - .env

  nextjs-app-3:
    build: .
    ports:
      - "3003:3000"
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextjs-app-1
      - nextjs-app-2
      - nextjs-app-3
